# Generated by Django 3.2 on 2021-04-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
                ('languages', models.CharField(max_length=50)),
            ],
        ),
    ]
