# Generated by Django 3.2 on 2021-04-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Address',
            field=models.CharField(default='adress', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(default='blood group', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='gender', max_length=50),
        ),
    ]
