# Generated by Django 3.2 on 2021-05-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210506_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='', upload_to='userphoto'),
        ),
    ]
