# Generated by Django 3.2 on 2021-05-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
