# Generated by Django 3.2 on 2021-04-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Detail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('primary_location', models.CharField(max_length=100)),
                ('type_doctor', models.CharField(max_length=50)),
                ('languages', models.CharField(max_length=100)),
                ('surgeon', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
    ]
