# Generated by Django 3.2 on 2021-04-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_detail',
            name='d_comment_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor_detail',
            name='d_patient_satis_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor_detail',
            name='d_rating',
            field=models.FloatField(default=4.5),
        ),
        migrations.AddField(
            model_name='doctor_detail',
            name='doc_email',
            field=models.EmailField(default=' ', max_length=254),
        ),
        migrations.AddField(
            model_name='doctor_detail',
            name='doc_phone',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
