# Generated by Django 3.2 on 2021-05-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_doctor_detail_d_comment_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_detail',
            name='certificate1',
            field=models.ImageField(default=' ', upload_to='doctor_certificates'),
        ),
        migrations.AddField(
            model_name='doctor_detail',
            name='certificate2',
            field=models.ImageField(default=' ', upload_to='doctor_certificates'),
        ),
        migrations.AddField(
            model_name='doctor_detail',
            name='certificate3',
            field=models.ImageField(default=' ', upload_to='doctor_certificates'),
        ),
        migrations.AddField(
            model_name='doctor_detail',
            name='doc_phone2',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='doctor_detail',
            name='photo1',
            field=models.ImageField(default=' ', upload_to='doctor_photo'),
        ),
        migrations.AddField(
            model_name='doctor_detail',
            name='photo2',
            field=models.ImageField(default=' ', upload_to='doctor_photo'),
        ),
    ]
