# Generated by Django 3.2 on 2021-05-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_appointment_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_appointment_list',
            name='appointment_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor_appointment_list',
            name='date',
            field=models.DateField(default='2021-01-01'),
        ),
        migrations.AddField(
            model_name='doctor_appointment_list',
            name='time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctors_appointment',
            name='time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
