# Generated by Django 3.2 on 2021-05-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctor_appointment_list_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_appointment_list',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='doctor_appointment_list',
            old_name='appointment_no',
            new_name='no_appointment',
        ),
        migrations.RenameField(
            model_name='doctors_appointment',
            old_name='time',
            new_name='Time',
        ),
    ]
