# Generated by Django 3.2 on 2021-05-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20210513_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Now_Appointment_No',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_name', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=500)),
            ],
        ),
    ]
