# Generated by Django 3.2 on 2021-05-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_now_appointment_no'),
    ]


    
