# Generated by Django 3.2 on 2021-05-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_auto_20210515_0802'),
    ]


