# Generated by Django 3.2 on 2021-05-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_delete_doctors_appointment'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='new_doctors_appointment',
            name='pk_id',
        ),
        migrations.AddField(
            model_name='new_doctors_appointment',
            name='patient_id',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='new_doctors_appointment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
