# Generated by Django 3.2 on 2021-05-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_auto_20210515_0909'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='new_doctors_appointment',
            name='id',
        ),
        migrations.AlterField(
            model_name='new_doctors_appointment',
            name='appointment_no',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='new_doctors_appointment',
            name='patient_id',
            field=models.IntegerField(),
        ),
    ]
