# Generated by Django 3.2 on 2021-05-18 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_delete_doctors_appointment'),
    ]


