# Generated by Django 3.2 on 2021-05-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lab_type',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lab_id', models.IntegerField()),
                ('test_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Lab_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=10000)),
            ],
        ),
    ]
