# Generated by Django 3.2 on 2021-05-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_auto_20210502_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='certificate',
            field=models.ImageField(default=None, upload_to='lab_certificate'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='lab_photo',
            field=models.ImageField(default=None, upload_to='lab_photo'),
        ),
    ]
