# Generated by Django 3.2 on 2021-05-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_auto_20210502_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_type',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
