# Generated by Django 3.2 on 2021-05-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_alter_lab_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='certificate',
            field=models.ImageField(upload_to='lab_certificate/'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='lab_photo',
            field=models.ImageField(upload_to='lab_photo/'),
        ),
    ]
