# Generated by Django 3.2 on 2021-05-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_auto_20210503_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='certificate',
            field=models.ImageField(upload_to='lab_certificate'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='lab_photo',
            field=models.ImageField(upload_to='lab_photo'),
        ),
    ]
