# Generated by Django 3.2 on 2021-05-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0007_auto_20210503_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab_appointment_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_no', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('lab_id', models.IntegerField()),
                ('doctor_appointment_no', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
