# Generated by Django 3.2 on 2021-05-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0008_lab_appointment_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_appointment_list',
            name='doctor_appointment_no',
            field=models.IntegerField(null=True),
        ),
    ]
